"name"
"Elmhurst Hospital"
"Meadowlands Hospital"
"Mt. Sinai Roosevelt Hospital"
"St. Lukes Roosevelt Hospital"
"Meadowview Psychiatric hospital"
"Palisade Hospital"
"Holy Name Hospital"
"St. Joseph's Children Hospital"
"West Hudson Hospital"
"St. John's Hospital"
"Wyckoff heights Hospital"
"Lincoln Hospital"
"Sunnyside Mental Hospital"
"Hamptons Heritage Hospital"
"The Brooklyn Hospital Center"
"Wyckoff Hospital"
"Woodhull Medical Center"
"Wyckoff Heights Medical Center"
"Bellevue Hospital Center"
"Brooklyn VA Hospital"
"Bement Shoe Hospital"
"Cook County Hospital"
"Kings County Hospital"
"New York Methodist Hospital"
"Brooklyn Navy Yard Hospital"
"Kings County Hospital"
"Brookdale University Hospital"
"Interfaith Hospital"
"The Knickerbocker Hospital"
"St. Vincent Hospital Treatment Center"
"Kingsbrook Jewish Medical Center"
"Napolitano Hospital"
"Ellis Hospital"
"Beth Israel Medical Center"
"Mount Sinai Beth Israel"
"Laxis Hospital"
"Maimonides Medical Center"
"Kravis Children's Hospital"
"New York Presbyterian Hospital"
"Coler Hospital"
"Gracie Square Hospital"
"Lenox Hill Hospital"
"New York Foundling Hospital"
"Kaufman Children's Hospital"
"Wilzig Hospital"
"Christ Hospital"
"Hospital for Special Surgery"
"Metropolitan Hospital Center"
"St. Vincent Hospital"
"Greenville Hospital"
"Brookdale Hospital"
"HUMC Mountainside Hospital"
"Calvary Hospital"
"Richmond University Medical Center"
"Staten Island University Hospital"
"Bayley Seton Hospital"
"NYU Lutheran Medical Center"
"NYU Langone Medical Center"
"New York Hospital Queens"
"New York Presbyterian Hospital Weill Cornell Medical Center"
"K R M Hospital"
"Jersey City Medical Center"
"Memorial Sloan Kettering Hospital"
"SUNY Downstate"
"St. Mary's Hospital Of Brooklyn"
"Children's Specialized Hospital"
"New York Community Hospital"
"Mount Sinai Brooklyn"
"The Mount Sinai Hospital"
"Mount Sinai West"
"Mount Sinai Hospital Of Queens"
"Schneiders Children Hospital"
"Bayonne Hospital"
"New York Methodist Hospital"
"New York City Health and Hospitals Corporation"
"Hoboken University Medical Center"
"Flushing Hospital"
"Manhattan Eye, Ear, Nose & Throat Hospital"

